### ISSUE TITLE
MELPA?

### ISSUE THREAD

**Issue by manuel-uberti** [cbowdon/daemons.el#1]
Sorry, not an issue per se, more of a question: any chance you're going to put this on MELPA?

This is a package I'd definitely use. :)

**Comment by cbowdon** [comment]
Thanks for the support! I'm working on adding it to MELPA now.

**Comment by manuel-uberti** [comment]
Great, I'll close this one then.

**Comment by cbowdon** [comment]
PR: https://github.com/melpa/melpa/pull/5316

**Comment by manuel-uberti** [comment]
Yay, thank you :)
