### ISSUE TITLE
Feature requests: enable/disable services and others

### ISSUE THREAD

**Issue by yyr** [cbowdon/daemons.el#12]
I only use debian based machines as of now, so i have `systemd` installed, the following features requests may only pertain to `systemd`.

- [x] key-commands for enable/disable services.

- [x] Sorting the services by status (enabled/disabled/masked  etc..)

- [x] Caching root password for some time (some packages (I dont remember which, tramp may be?) don't ask for password each time) , or even better an option to start the daemons  as super user (Ideally with warning banner on top saying "running daemons as root, be careful" or something)

 
If I need any other I will add here. 

Thank you.

**Comment by cbowdon** [comment]
These are some very good ideas and I'd like to see them all in daemons.el one day. Happily, some of this is already available!

You can currently sort services by status by clicking the column header or `M-x tabulated-list-sort` with the cursor in a given column. This is part of the standard `tabulated-list` functionality. Perhaps it would be nice bind this to a key in daemons-mode though.

For password caching, try `M-x customize-group password`, which is what I think tramp is using.

You can currently set the custom variable `daemons-always-sudo` to achieve the super user behaviour. In the new version (the buffer-per-host branch just merged to master) you can also start daemons by navigating to a super user context with tramp:

```
M-x cd /sudo::
M-x daemons
```

In this scenario the buffer is named `*daemons for root@hostname*`, which isn't quite as good as a banner warning but at least gives you something to check. 

Enabling/disabling services should be possible just by adding bindings to `daemons-mode-map` and creating functions `daemons-enable` and `daemons-enable-at-point`. The commands alist would then need to be updated for each submodule.

**Comment by yyr** [comment]
> You can currently sort services by status by clicking the column header or M-x tabulated-list-sort with the cursor in a given column.

That was my first guess, but then I clicked header `Enabled` button with mouse.. and I see `<header-line> <header-line> <mouse-2> is undefined` in the minibuffer. so sorting function hasn't been bound to the mouse.

and thank you for letting me know the workaround, I will use them for now.

Thanks

**Comment by cbowdon** [comment]
Shouldn't a primary click be `mouse-1` not `mouse-2`? It is for me. Perhaps it's a mouse configuration thing.

**Comment by cbowdon** [comment]
I've finally got round to implementing enable/disable for systemd, so I think your three feature requests are now complete! I'm closing the ticket, feel free to reopen if you have issues.
