### ISSUE TITLE
Handle templated systemd services

### ISSUE THREAD

**Issue by Stebalien** [cbowdon/daemons.el#2]
Currently, services-mode displays the *template* but not instantiated templated services. For example, it lists `getty@` but not `getty@tty1`.

Also, hitting `RET` on a template doesn't do anything useful (it opens a buffer that displays "Failed to get properties: Unit name thing@.service is neither a valid invocation ID nor unit name.").

I don't have any strong opinons on how these services should be handled, but they should be handled somehow (e.g., being able to stop `getty@ttyN.service` would be nice).

---

(Also, awesome project! I've been looking for something like this for a while. I currently have a set of ivy commands but this is much nicer).

**Comment by cbowdon** [comment]
Thanks for giving this a try and for the kind words!

I'll see what I can do about template services, the current behaviour is indeed a bit rubbish. Ideally there would be some `systemctl` command I can run that shows these too. (At the moment the list is based around `list-unit-files`).

**Comment by Stebalien** [comment]
Take a look at the systemd dbus interface and the dbus emacs package. Emacs has a nice dbus library so, personally, I find it a lot more usable than parsing the output of systemctl.

**Comment by cbowdon** [comment]
https://github.com/cbowdon/daemons.el/commit/285989cd5aea081bcfd917125f4e60de3356ef25 is not a solution btw, just a placeholder. :-)

**Comment by cbowdon** [comment]
Sorry, no update on this as I don't have the time right now. A PR would of course be welcome.
