### ISSUE TITLE
Systemd user services

### ISSUE THREAD

**Issue by deadtrickster** [cbowdon/daemons.el#3]
Hi, cool package, thank you!

I just noticed that my emacs-daemon service which is running as systemd --user server isn't listed. Is that expected?

**Comment by cbowdon** [comment]
Thanks! It's a known issue that I would like to resolve (template services too, see #2). The proposed solution there (using systemd's dbus interface) would probably enable resolving this too.

I'm intending to tackle that at some point, but a PR to get it done sooner would also be welcome.

**Comment by sebastiencs** [comment]
+1. Thanks for the package @cbowdon
