### ISSUE TITLE
`shell-command` and friends consistently output messages

### ISSUE THREAD

**Issue by jellelicht** [cbowdon/daemons.el#34]
See title.

Snippet of my *Messages* buffer:

```
which: no systemctl in (<MYPATH>)
which: no service in (<MYPATH>)
```

Would using `call-process` instead be an option?

**Comment by cbowdon** [comment]
My elisp skills have atrophied over the years, but as far as I can see this is feasible but a bit tedious because a load of format strings will need to be converted into lists of strings. Wonder if perhaps there's another reason (and solution) for these messages?

**Comment by jellelicht** [comment]
I went with something that's hopefully simpler and requires less rework. Please have a look at your leisure

**Comment by cbowdon** [comment]
Fix merged, thanks!
