### ISSUE TITLE
 Symbol’s function definition is void: tramp-file-name-real-user

### ISSUE THREAD

**Issue by steckerhalter** [cbowdon/daemons.el#9]
This is with the `buffer-per-host` branch. Maybe that function got removed in Emacs trunk (which I am using)?

**Comment by steckerhalter** [comment]
```diff
 commit dca22e86e02d16a31128c163925b13404f777c0f
Author: Michael Albinus <michael.albinus@gmx.de>
Date:   Wed May 24 16:16:53 2017 +0200

    Introduce a defstruct `tramp-file-name' as central data structure.
    
    This solves also Bug#27009.
    
    * lisp/net/tramp.el (tramp-current-domain)
    (tramp-current-port): New defvars.
    (tramp-file-name): New defstruct.
    (tramp-file-name-user-domain, tramp-file-name-host-port)
    (tramp-file-name-equal-p): New defuns.
    (tramp-file-name-p, tramp-file-name-method)
    (tramp-file-name-user, tramp-file-name-host)
    (tramp-file-name-localname, tramp-file-name-hop)
    (tramp-file-name-real-user, tramp-file-name-domain)
    (tramp-file-name-real-host, tramp-file-name-port):
    Remove defuns.  They are provided by the defstruct, or not
    needed anymore.

...
```

**Comment by cbowdon** [comment]
Hey, huge thanks for giving it a try! I’ll check it out.

**Comment by cbowdon** [comment]
Stumbled across some other packages that are facing the same issue. I might wait and copy their solution. I want to support both versions for at least some time.

**Comment by cbowdon** [comment]
Never mind, it was a trivial fix. Thank you very much for locating that commit :-)

I've tested this on Emacs 26. If you'd like to have another go that would be great, otherwise I'll close this ticket in a couple of days. Remote systems ticket #4 is still open (but nearly there).

**Comment by steckerhalter** [comment]
thanks, it works now. what I noticed is that on the remote system ansi color codes are messing up the UI

**Comment by cbowdon** [comment]
Thanks! Will look into remote color codes separately.
